#!/usr/bin/env python3

import sys;

pc = 0

values = []
for line in sys.stdin:
    for val in line.strip().split(","):
        values.append(val)

ix = 0

OPCODES = {
    1: 'ADD',
    2: 'MULTIPLY',
    3: 'INPUT',
    4: 'OUTPUT',
    5: 'JUMP TRUE',
    6: 'JUMP FALSE',
    7: 'LESS THAN',
    8: 'EQUALS',
    9: 'RELBASE',
    99: 'HALT',
}

WIDTHS = {
    1: 4,
    2: 4,
    3: 2,
    4: 2,
    5: 3,
    6: 3,
    7: 4,
    8: 4,
    9: 2,
    99: 1,
}


def show_bytes(ix, opcode, desc, width):
    data = values[ix:ix+width]

    modifier  = opcode // 100
    modifier1 = modifier % 10
    modifier2 = (modifier // 10) % 10
    modifier3 = (modifier // 100) % 100
    if width > 1:
        if modifier1 == 0:
            data[1] = f"M[{data[1]}]"
        elif modifier1 == 2:
            data[1] = f"R[{data[1]}]"
    if width > 2:
        if modifier2 == 0:
            data[2] = f"M[{data[2]}]"
        elif modifier2 == 2:
            data[2] = f"R[{data[2]}]"
    if width > 3:
        if modifier3 == 2:
            data[3] = f"-> R[{data[3]}]"
        else:
            data[3] = f"-> M[{data[3]}]"
    data_str = " ".join(data)
    print(f"{ix:04} {desc:10} -- {data_str}")


while True:
    if ix >= len(values):
        break
    val = int(values[ix])
    opcode = val % 100
    if opcode in WIDTHS:
        width = WIDTHS[opcode]
        desc = OPCODES[opcode]
    else:
        width = 1
        desc = "DATA"
    show_bytes(ix, val, desc, width)
    ix += width
